# подключение к базе данных
url: jdbc:postgresql://localhost:5432/kaserv
user: EXTUSER
password: 123456

# база с которой идет обмен
baseID: 1

# файл для обмена данных БД
obmenURL: C:\Users\kaserv\Desktop\ObmenTests\ObmenFiles

# задержка времени начала работы программы и период выполнения обмена данных в мс
delay: 30000
period: 30000